#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev'); //dev-开发&&测试环境  online-线上环境

//框架根目录
define('__ROOT__', __DIR__);

require(__ROOT__ . '/vendor/autoload.php');
require(__ROOT__ . '/vendor/yiisoft/yii2/Yii.php');
require(__ROOT__ . '/common/config/bootstrap.php');
require(__ROOT__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__ROOT__ . '/common/config/main.php'),
    require(__ROOT__ . '/console/config/main.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
